modules/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    name = StringField('login', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Submit')


class MessageSendForm(FlaskForm):
    recipient = StringField('recipient', validators=[DataRequired()])
    text = TextAreaField('text', validators=[DataRequired()])
    submit = SubmitField('Submit')

app.py
from flask import Flask
from flask_bootstrap import Bootstrap
from modules import views


application = Flask(__name__)
application.testing = True
application.secret_key = b'_5#y2L"F4Q8z\n\xec]/'


if __name__ == "__main__":
    Bootstrap(application)
    application.register_blueprint(views.bp)
    application.run(debug=True)

modules/views.py
import json
from flask import Blueprint, request
from flask import render_template, redirect, url_for, make_response
from modules import forms
from Cryptodome.PublicKey import RSA
from Cryptodome.Cipher import PKCS1_v1_5
import base64

from modules import servereqs
from cryptography.hazmat.primitives.serialization import load_pem_public_key
from cryptography.hazmat.backends import default_backend


bp = Blueprint('views', __name__)
key_list = []
user_data = []


server_key = load_pem_public_key(
        open('server_public.pem').read().encode(),
        backend=default_backend()
)


@bp.route("/test")
def test():
    return 'hello world'


@bp.route("/", methods=['GET', 'POST'])
@bp.route("/home", methods=['GET', 'POST'])
def home():
    global user_data
    form = forms.MessageSendForm()
    user_token = request.cookies.get('user_token')
    username = request.cookies.get('username')
    print(user_token, username)
    profile = None
    for i in user_data:
        if i['username'] == username:
            profile = i
    if not profile:
        return("Not autorized")
    profile['username']
    messages = None
    try:
        messages = servereqs.get_messages(
            profile['username'],
            user_token,
            profile['key_pair'],
            server_key
        )
    except Exception as e:
        page_info = 'Ошибка получения сообщений'
    if not messages:
        messages = []
    if form.validate_on_submit():
        try:
            servereqs.send_message(
                profile['username'],
                form.recipient.data,
                form.text.data,
                user_token,
                profile['key_pair'],
                server_key
            )
            page_info = 'Сообщение отправлено'
        except Exception as e:
            page_info = 'Сообщение не отправлено'
        return render_template(
            'home.html',
            messages=messages,
            form=form,
            message=page_info
        )
    return render_template(
        'home.html',
        messages=messages,
        form=form,
        message=''
    )


@bp.route("/registration", methods=['GET', 'POST'])
def registration():
    global key_list
    form = forms.LoginForm()
    ermessage = ''
    keyPair = RSA.generate(1024)
    public_key = keyPair.publickey()
    pubKey = public_key.exportKey().decode('ascii')
    key_list.append(
        {
            "public": pubKey,
            "key_pair": keyPair,
        }
    )
    if request.method == 'POST':
        return redirect(url_for('views.home'))
    return render_template(
        'registration.html',
        form=form,
        error=ermessage,
        key=pubKey
    )


@bp.route("/login", methods=['GET', 'POST'])
def login():
    global key_list
    form = forms.LoginForm()
    ermessage = ''
    keyPair = RSA.generate(1024)
    public_key = keyPair.publickey()
    pubKey = public_key.exportKey().decode('ascii')
    key_list.append(
        {
            "public": pubKey,
            "key_pair": keyPair,
        }
    )
    if request.method == 'POST':
        return redirect(url_for('views.home'))
    return render_template(
        'login.html',
        form=form,
        error=ermessage,
        key=pubKey
    )


@bp.route("/jsautorize", methods=['GET', 'POST'])
def jsautorize():
    data = request.get_json(force=True)
    global key_list
    global user_data
    key_Pair = None
    for i in key_list:
        if data["public_key"][27:-25].replace("\n", "") == i["public"][27:-25].replace("\n", ""):
            key_Pair = i['key_pair']
            break
    if key_Pair:
        ciphertext = base64.b64decode(data["ciphertext"])
        cipher = PKCS1_v1_5.new(key_Pair)
        plain_text = cipher.decrypt(ciphertext, 'bollox')
        password = plain_text.decode("utf-8")
        user_token = None
        try:
            user_token = servereqs.authorization(data["username"], password, key_Pair, server_key)
            for i in user_data:
                if i['username'] == data["username"]:
                    user_data.remove(i)
            user_data.append({
                "username": data["username"],
                "password": password,
                "key_pair": key_Pair
            })
        except Exception as e:
            print(e)
        if user_token:
            resp = make_response("The Cookie has been set")
            resp.set_cookie('user_token', user_token)
            resp.set_cookie("username", data["username"])
        return resp

    else:
        print('not found', data["public_key"][27:-25])
        return (
            json.dumps({'info': 'keypain not found'}),
            200,
            {'ContentType': 'application/json'}
        )


@bp.route("/jsregistr", methods=['GET', 'POST'])
def jsregistr():
    data = request.get_json(force=True)
    global key_list
    global user_data
    key_Pair = None
    for i in key_list:
        if data["public_key"][27:-25].replace("\n", "") == i["public"][27:-25].replace("\n", ""):
            key_Pair = i['key_pair']
            break
    if key_Pair:
        ciphertext = base64.b64decode(data["ciphertext"])
        cipher = PKCS1_v1_5.new(key_Pair)
        plain_text = cipher.decrypt(ciphertext, 'bollox')
        password = plain_text.decode("utf-8")
        user_token = None
        try:
            user_token = servereqs.registration(data["username"], password, key_Pair, server_key)
            for i in user_data:
                if i['username'] == data["username"]:
                    user_data.remove(i)
            user_data.append({
                "username": data["username"],
                "password": password,
                "key_pair": key_Pair
            })
        except Exception as e:
            print(e)
        if user_token:
            resp = make_response("The Cookie has been set")
            resp.set_cookie('user_token', user_token)
            resp.set_cookie("username", data["username"])
            return resp

    else:
        print('not found', data["public_key"][27:-25])
        return (
            json.dumps({'info': 'keypain not found'}),
            200,
            {'ContentType': 'application/json'}
        )

templates/home.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
	<style>
		body { background: #e8f1f9; }
	</style>
{% endblock %}
{% block title %}
Главная
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">
      <h1 class="pt-5 pb-2">Полученные сообщения</h1>
      <table style="width:100%">
        <tr>
          <th>Время</th>
          <th>от</th>
          <th>текст</th>
        </tr>
        {%for i in messages%}
        <tr>
            <td>{{i['time']}}</td>
            <td>{{i['from']}}</td>
            <td>{{i['text']}}</td>
        </tr>
        {%endfor%}
      </table>
      <br>
      <br>
      <h1 class="pt-5 pb-2">Отправить сообщение</h1>
      <form method="POST" action="" style="width:100%">
        {{ form.csrf_token }}
        <h3>Получатель</h3>
        {{ form.recipient() }} 
        <br>
        <h3>Текст</h3>
        {{ form.text(rows='2',cols='100')}}
        {{ form.submit() }}
      </form>
      <p>{{message}}</p>
    </div>
  </div>
</div>

{% endblock %}

templates/login.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
	<style>
		body { background: #e8f1f9; }
	</style>
{% endblock %}
{% block title %}
Регистрация
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

      <h1 class="pt-5 pb-2">Зарегистрироваться</h1>
      <form method="POST" action="">
        {{ form.csrf_token }}
        <h3>Login</h3>
        <input id="name">
        <br>
        <h3>Password</h3>
        <input id="password">
        <br>
        <input type="hidden" id="public_key" value="{{ key }}">
        <input type="hidden" id="url" value="{{ url_for('views.jsautorize') }}">
        <br>
        {{ form.submit(onclick="encrypt()") }}
      </form>

      <p class="pt-5"><strong>{{ error }}</strong></p>
      <a href="{{ url_for('views.registration') }}">Зарегистрироваться</a>
      <script src="https://cdn.jsdelivr.net/npm/node-forge@1.0.0/dist/forge.min.js"></script>
      <script>
        async function encrypt()
        {
          var name=document.getElementById('name').value;
          var pass=document.getElementById('password').value;
          var public_key=document.getElementById('public_key').value;
          var publicKey = forge.pki.publicKeyFromPem(public_key);
          var ciphertext = publicKey.encrypt(pass, "RSAES-PKCS1-V1_5");
          var base64 = forge.util.encode64(ciphertext);
          //
          url = document.getElementById('url').value;
          let response = fetch(url, {
            method: 'POST',
            body: JSON.stringify({"username": name,"ciphertext": base64, "public_key": public_key}),
          });
        }
        
      </script>
    </div>
  </div>
</div>

{% endblock %}

templates/registration.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
	<style>
		body { background: #e8f1f9; }
	</style>
{% endblock %}


{% block title %}
Регистрация
{% endblock %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

      <h1 class="pt-5 pb-2">Зарегистрироваться</h1>
      <form method="POST" action="">
        {{ form.csrf_token }}
        <h3>Login</h3>
        <input id="name">
        <br>
        <h3>Password</h3>
        <input id="password">
        <br>
        <input type="hidden" id="public_key" value="{{ key }}">
        <input type="hidden" id="url" value="{{ url_for('views.jsregistr') }}">
        <br>
        {{ form.submit(onclick="encrypt()") }}
      </form>

      <p class="pt-5"><strong>{{ error }}</strong></p>
      <script src="https://cdn.jsdelivr.net/npm/node-forge@1.0.0/dist/forge.min.js"></script>
      <script>
        async function encrypt()
        {
          var name=document.getElementById('name').value;
          var pass=document.getElementById('password').value;
          var public_key=document.getElementById('public_key').value;
          var publicKey = forge.pki.publicKeyFromPem(public_key);
          var ciphertext = publicKey.encrypt(pass, "RSAES-PKCS1-V1_5");
          var base64 = forge.util.encode64(ciphertext);
          //
          url = document.getElementById('url').value;
          let response = fetch(url, {
            method: 'POST',
            body: JSON.stringify({"username": name,"ciphertext": base64, "public_key": public_key}),
          });
        }
        
      </script>
    </div>
  </div>
</div>

{% endblock %}